openapi: 3.0.0
info:
    version: 1.0.0
    contact:
        name: Spryker
        url: 'https://spryker.com/'
        email: support@spryker.com
    title: 'Spryker Webhook API'
    license:
        name: Proprietary

servers:
    -   url: 'http://api.web-hook.spryker.local'
        description: 'Local glue endpoint'
    -   url: 'https://api.web-hook-testing.acp.demo-spryker.com/'
        description: 'Testing glue endpoint'
    -   url: 'https://api.web-hook-staging.acp.demo-spryker.com/'
        description: 'Staging glue endpoint'
    -   url: 'https://api.web-hook.acp.spryker.com/'
        description: 'Production glue endpoint'

paths:
    '/webhooks':
        post:
            x-spryker:
                module: AppWebhookBackendApi
                controller: WebhooksController
            summary: 'Endpoint used by third party providers to send webhooks to.'
            requestBody:
                description: 'Webhook data.'
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/WebhookRequest'
            responses:
                200:
                    description: 'Expected response to a valid request.'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/WebhookResponse'
                400:
                    description: 'Bad request.'
                default:
                    description: 'Expected response to a bad request.'
                    content:
                        text/plain:
                            schema:
                                type: string

    '/webhooks/test':
        post:
            x-spryker:
                module: AppWebhookBackendApi
                controller: WebhooksController
            summary: 'Endpoint used by third party providers to send webhooks to in test mode.'
            requestBody:
                description: 'Webhook data.'
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/WebhookRequest'
            responses:
                200:
                    description: 'Expected response to a valid request.'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/WebhookResponse'
                400:
                    description: 'Bad request.'
                default:
                    description: 'Expected response to a bad request.'
                    content:
                        text/plain:
                            schema:
                                type: string

components:
    schemas:
        WebhookRequest:
            properties:
                content:
                    type: string
        WebhookResponse:
            properties:
                isSuccessful:
                    type: boolean
